### PR TITLE
Add HTML related syntax scope tokens

### PR DESCRIPTION
**Pull request by jasontheiler**
Hi Matt,

these are the two little changes I mentioned in issue #17. They would result in something that looks like this, which obviously isn't the way to go, though:

HTML/Vue template

I think you'd have to remove the scope tokens in the lines 293-295 to get something that looks alright in both HTML/Vue template and JSX. But then the element tags (`<>`) would be in the foreground color 😕 

Also, here's an example Vue component that includes `<template>`, `<script>` and `<style>` sections:

> Keep in mind that you'll need the [Vetur extension](https://marketplace.visualstudio.com/items?itemName=octref.vetur) to get proper syntax highlighting in `.vue` files!

```vue
<template>
  <div class="counter">
    <CounterDisplay :count="count" />

    <AppButton variant="secondary" @click="() => increment()">
      Increment
    </AppButton>
  </div>
</template>

<script>
import { defineComponent, ref } from "vue";

export default defineComponent({
  setup() {
    const count = ref(0);

    const increment = () => (count.value += 1);

    return {
      count,
      increment,
    };
  },
});
</script>

<style scoped>
.counter {
  width: 100%;
  padding: 1rem 2rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>
```

### CODE REVIEW

**Comment by gleich** [comment]
So I removed `"meta.tag.block.any.html"` on line 301 and the end tag for `AppButton` seems to still work. I've never used Vue before so lemme know if the file I have in the screenshot below isn't valid. Is it possible that you have some extension installed that could be breaking it? It would be super helpful if you could send me a screenshot of your editor inspector tokens when your cursor is on the closing tag. The second image shows mine.

Screen Shot 2021-07-10 at 2 24 50 PM
Screen Shot 2021-07-10 at 2 26 32 PM

**Comment by jasontheiler** [comment]
Well ... the editor tokens seem to be the same as yours and should definitely be correct. Heck, it even shows `#5A637E` as the foreground color but my editor actually colors it with `#FDF7CD`...

image

I tried disabling all extensions (except for Vetur obviously) but that still doesn't fix it.

Anyway, it probably means that the theme is actually fine and the problem with the end tag is somewhere else in my VS Code ... sorry that I didn't notice it before.

I removed that editor token from the PR now :)

**Review by gleich — APPROVED** [review]
Looks good to me! Thanks for this Jason!

**Comment by gleich** [comment]
Ok, sounds good. Lemme know if you need any help tracking it down.

**Comment by jasontheiler** [comment]
I probably just won't bother for now ... too busy atm. :/

But thank you!

**Pull request merged**
